class PostSweeper < ActionController::Caching::Sweeper
  
  observe Post
  
  def after_create(post)    
    FileUtils.rm_rf File.expand_path("public/index.html", RAILS_ROOT)
    FileUtils.rm_rf File.expand_path("public/popular.html", RAILS_ROOT)
    FileUtils.rm_rf File.expand_path("public/covers.html", RAILS_ROOT)
    FileUtils.rm_rf File.expand_path("public/news.html", RAILS_ROOT)
    FileUtils.rm_rf File.expand_path("public/business.html", RAILS_ROOT)
    FileUtils.rm_rf File.expand_path("public/sports.html", RAILS_ROOT)
    FileUtils.rm_rf File.expand_path("public/popular/", RAILS_ROOT)
    FileUtils.rm_rf File.expand_path("public/covers/", RAILS_ROOT)
    FileUtils.rm_rf File.expand_path("public/news/", RAILS_ROOT)
    FileUtils.rm_rf File.expand_path("public/business/", RAILS_ROOT)
    FileUtils.rm_rf File.expand_path("public/sports/", RAILS_ROOT)    
    FileUtils.rm_rf File.expand_path("public/1.html", RAILS_ROOT)
    FileUtils.rm_rf File.expand_path("public/2.html", RAILS_ROOT)
    FileUtils.rm_rf File.expand_path("public/3.html", RAILS_ROOT)
    FileUtils.rm_rf File.expand_path("public/4.html", RAILS_ROOT)
    FileUtils.rm_rf File.expand_path("public/5.html", RAILS_ROOT)
    FileUtils.rm_rf File.expand_path("public/6.html", RAILS_ROOT)
    FileUtils.rm_rf File.expand_path("public/7.html", RAILS_ROOT)
    FileUtils.rm_rf File.expand_path("public/8.html", RAILS_ROOT)
    FileUtils.rm_rf File.expand_path("public/9.html", RAILS_ROOT)
    FileUtils.rm_rf File.expand_path("public/10.html", RAILS_ROOT)
    FileUtils.rm_rf File.expand_path("public/11.html", RAILS_ROOT)    
    FileUtils.rm_rf File.expand_path("public/12.html", RAILS_ROOT)
    FileUtils.rm_rf File.expand_path("public/13.html", RAILS_ROOT)
    FileUtils.rm_rf File.expand_path("public/14.html", RAILS_ROOT)
    FileUtils.rm_rf File.expand_path("public/15.html", RAILS_ROOT)    
    FileUtils.rm_rf File.expand_path("public/16.html", RAILS_ROOT)
    FileUtils.rm_rf File.expand_path("public/17.html", RAILS_ROOT)
    FileUtils.rm_rf File.expand_path("public/18.html", RAILS_ROOT)
    FileUtils.rm_rf File.expand_path("public/19.html", RAILS_ROOT)
    FileUtils.rm_rf File.expand_path("public/20.html", RAILS_ROOT)
    FileUtils.rm_rf File.expand_path("public/21.html", RAILS_ROOT)
    FileUtils.rm_rf File.expand_path("public/22.html", RAILS_ROOT)
    FileUtils.rm_rf File.expand_path("public/23.html", RAILS_ROOT)
    FileUtils.rm_rf File.expand_path("public/24.html", RAILS_ROOT)
    FileUtils.rm_rf File.expand_path("public/25.html", RAILS_ROOT)
    FileUtils.rm_rf File.expand_path("public/26.html", RAILS_ROOT)
    FileUtils.rm_rf File.expand_path("public/27.html", RAILS_ROOT)
    FileUtils.rm_rf File.expand_path("public/28.html", RAILS_ROOT)
    FileUtils.rm_rf File.expand_path("public/29.html", RAILS_ROOT)
    FileUtils.rm_rf File.expand_path("public/30.html", RAILS_ROOT)        
  end
end